functions:
  "fetch_source":
    - command: git.get_project
      params:
        directory: "baas-js-sdk"

  "setup_mongod":
    - command: shell.exec
      params:
        script: |
          set -v
          curl --silent ${mongodb_url} | tar xvz
    - command: shell.exec
      params:
        background: true
        script: |
          set -v
          cd mongodb-*
          echo "starting mongod..."
          mkdir db_files
          ./bin/mongod --dbpath ./db_files --port 27017 &
          echo "waiting for mongod to start up"
    - command: shell.exec
      params:
        script: |
          set -e
          cd mongodb-*
          ./bin/mongo --nodb --eval 'assert.soon(function(x){try{var d = new Mongo("localhost:27017"); return true}catch(e){return false}}, "timed out connecting")'
          echo "mongod is up."

  "setup_baas":
    - command: shell.exec
      params:
        script: |
          set -e
          echo "cloning baas"
          mkdir -p src/github.com/10gen
          git clone git@github.com:10gen/baas src/github.com/10gen/baas

          echo "downloading libmongo"
          wget --quiet "https://s3.amazonaws.com/baas-tools/libmongo.so"
          chmod +x libmongo.so
    - command: shell.exec
      params:
        background: true
        script: |
          export GOPATH=`pwd`
          export PATH="`pwd`:$PATH"
          export BAAS_PATH=$GOPATH/src/github.com/10gen/baas
          cd baas-js-sdk/test/bin
          echo "running baas"
          go run $BAAS_PATH/main/main.go --configFile ../conf/test_config.json

tasks:
  - name: run_tests
    commands:
      - func: "fetch_source"
      - func: "setup_mongod"
      - func: "setup_baas"
      - command: shell.exec
        params:
          script: |
            set -e
            echo "running client tests"
            cd baas-js-sdk
            npm install
            npm test

  - name: dist
    depends_on:
      - name: run_tests
    commands:
      - func: "fetch_source"
      - command: shell.exec
        params:
          script: |
            set -e
            cd baas-js-sdk
            npm install
            npm run build
            npm pack

      - command: s3.put
        params:
          aws_key: ${sdks_aws_key}
          aws_secret: ${sdks_aws_secret}
          local_file: baas-js-sdk/dist/baas.js
          remote_file: js/npm/${revision}/baas.js
          bucket: baas-sdks
          permissions: public-read
          content_type: application/javascript
          display_name: BaaS Javascript Library

      - command: s3.put
        params:
          aws_key: ${sdks_aws_key}
          aws_secret: ${sdks_aws_secret}
          local_file: baas-js-sdk/dist/baas.min.js
          remote_file: js/npm/${revision}/baas.min.js
          bucket: baas-sdks
          permissions: public-read
          content_type: application/javascript
          display_name: BaaS Javascript Library (minified)

      - command: s3.put
        params:
          aws_key: ${sdks_aws_key}
          aws_secret: ${sdks_aws_secret}
          local_file: baas-js-sdk/baas-1.0.0.tgz
          remote_file: js/npm/${revision}/baas.tgz
          bucket: baas-sdks
          permissions: public-read
          content_type: application/gzip
          display_name: BaaS NPM package

  - name: docs_dist
    depends_on:
      - name: run_tests
    commands:
      - func: "fetch_source"
      - command: shell.exec
        params:
          script: |
            set -e
            cd baas-js-sdk
            npm install
            npm run docs
      - command: s3.put
        params:
          aws_key: ${sdks_aws_key}
          aws_secret: ${sdks_aws_secret}
          local_files_include_filter: ["baas-js-sdk/docs/*/*"]
          remote_file: js/docs/${revision}/baas.min.js
          bucket: baas-sdks
          permissions: public-read
          content_type: text/html

buildvariants:
- name: linux-64
  display_name: Linux-64
  run_on:
    - baas-linux
  expansions:
    mongodb_url: http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.4.1.tgz
  tasks:
    - name: run_tests
    - name: dist
    - name: docs_dist
